on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
#    container: ghcr.io/its-the-final/gha-kvm:latest
    steps:
      - uses: actions/checkout@v4

#      - uses: ilammy/setup-nasm@v1

      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v4
        with:
          path: alpine-x86_64.qcow2
          key: ${{ runner.os }}-primes
  
      - name: Prepare Boot-Man demo
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: |
          #git clone https://github.com/guyhill/Boot-Man
          #cd Boot-Man
          #make
          bash -c "time wget -q -c -O alpine-x86_64.qcow2 https://dl-cdn.alpinelinux.org/alpine/v3.22/releases/cloud/nocloud_alpine-3.22.1-x86_64-bios-cloudinit-r0.qcow2"
          #wget -q -c https://cloud.debian.org/images/cloud/bullseye-backports/20250703-2162/debian-11-backports-nocloud-amd64-20250703-2162.tar.xz
          #tar --xz -xf debian-11-backports-nocloud-amd64-20250703-2162.tar.xz
          #ln -s debian-11-backports-nocloud-amd64-20250703-2162.raw alpine-x86_64.img
          #which qemu-img|| sudo apt-get update && sudo apt-get -y install qemu-utils;  
          bash -c "time  qemu-img resize alpine-x86_64.qcow2 +32G"

      #- name: PREPARE qemu
      #  id: prepareqemu
      #  run: bash prepare-cloudinit.sh ; which curl || apt-get -y --no-install-recommends curl;which python3 || apt-get -y --no-install-recommends python3 ;cd cinit;pwd;python3 -m http.server --directory . &  sleep 2;curl 127.0.0.1:8000;echo;echo;ipconfig="myip="$(ip a|grep eth0|grep inet|grep -v inet6|cut -dt -f2|cut -d/ -f1|head -n1|cut -d" " -f2);echo $ipconfig;echo $ipconfig >> $GITHUB_OUTPUT
#      - name: install action
#        id: action-install
#        run: git clone https://github.com/etchdroid/qemu-kvm-action.git
      - name: Setup QEMU
        uses: etchdroid/qemu-kvm-action/setup@v1
        with:
          video-record: true
        env:
          DEBIAN_FRONTEND: noninteractive
          TERM: linux
      - name: create fifos
        run:  mkfifo /tmp/guest.in /tmp/guest.out
      - name: Run QEMU
        id: run-qemu
        uses: etchdroid/qemu-kvm-action@v1
        with:
          video-record: true
          #flags: 'Boot-Man/boot-man.bin'
          flags: |
            -serial
            pipe:/tmp/guest
            -enable-kvm
            -drive
            id=disk,file=alpine-x86_64.qcow2,if=none
            -device
            ahci,id=ahci
            -device
            ide-hd,drive=disk,bus=ahci.0
            -drive
            id=cidata,file=seed.img,if=none
            -device
            ide-hd,drive=cidata,bus=ahci.1

          run: echo provisioning from ${{ steps.prepareqemu.outputs.myip }} ;cat /tmp/guest.out & sleep 60 ; ( echo timmy;sleep 1;echo password ;sleep 5;echo 'bash -c "while (true);do ssh qemukvmtest@ssh-j.com -N -R qemukvm:22:localhost:22 ;done" & ' ; echo 'sudo bash -c "echo asd"'; echo 'doas bash -c "echo asd;echo ttyS0 >>/dev/ttyS0 ; echo ttyAMA0 >> /dev/ttyAMA0"';sleep 1;echo password ;sleep 2;echo uptime;echo nproc;echo id -u ; echo ifconfig ;echo df -h ;sleep 3) > /tmp/guest.in & sleep 600
#            -smbios
#            type=1,serial=ds='nocloud;s=http://10.0.2.2:8000/'

            #  -monitor
          #  pipe:/tmp/guest
#            type=1,serial=ds='nocloud;s=http://${{ steps.prepareqemu.outputs.myip }}:8000/'
          #run: cat /tmp/guest.out & sleep 60 ;(echo sendkey r ;echo sendkey o ;echo sendkey o ;echo sendkey t;echo sendkey ret ;echo sendkey r ;echo sendkey o ;echo sendkey o ;echo sendkey t;echo sendkey ret ; echo sendkey t;echo sendkey o ;echo sendkey p;echo sendkey ret;sleep 2 ) > /tmp/guest.in; sleep 20

      - name: Upload video
        uses: actions/upload-artifact@v4
        with:
          name: recording
          path: ${{ steps.run-qemu.outputs.video-output }}
