on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

#      - uses: ilammy/setup-nasm@v1

      - name: Prepare Boot-Man demo
        run: |
          #git clone https://github.com/guyhill/Boot-Man
          #cd Boot-Man
          #make
          wget -c -O alpine-x86_64.img https://dl-cdn.alpinelinux.org/alpine/v3.22/releases/cloud/nocloud_alpine-3.22.1-x86_64-bios-tiny-r0.qcow2 
          mkfifo /tmp/guest.in /tmp/guest.out

      - name: Run QEMU
        id: run-qemu
        uses: etchdroid/qemu-kvm-action@v1
        with:
          video-record: true
          #flags: 'Boot-Man/boot-man.bin'
          flags: |
            -serial
            pipe:/tmp/guest
            -enable-kvm
            -smbios
            type=1,serial=ds='nocloud;s=http://10.0.2.2:8000/'
            alpine-x86_64.img
          run: cat /tmp/guest.out & sleep 60 ; ( echo alpine;sleep 1;echo myuserpassfortesting11 ;sleep 5;echo uptime;echo nproc;echo id -u ; echo ifconfig ;echo df -h ;sleep 3) > /tmp/guest.in; sleep 10 
          #  -monitor
          #  pipe:/tmp/guest
          #run: cat /tmp/guest.out & sleep 60 ;(echo sendkey r ;echo sendkey o ;echo sendkey o ;echo sendkey t;echo sendkey ret ;echo sendkey r ;echo sendkey o ;echo sendkey o ;echo sendkey t;echo sendkey ret ; echo sendkey t;echo sendkey o ;echo sendkey p;echo sendkey ret;sleep 2 ) > /tmp/guest.in; sleep 20

      - name: Upload video
        uses: actions/upload-artifact@v4
        with:
          name: recording
          path: ${{ steps.run-qemu.outputs.video-output }}
