on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    uses: etchdroid/qemu-kvm-action@v1
    steps:
      - uses: actions/checkout@v4

#      - uses: ilammy/setup-nasm@v1

      - name: Prepare Boot-Man demo
        run: |
          #git clone https://github.com/guyhill/Boot-Man
          #cd Boot-Man
          #make
          wget -c -O alpine-x86_64.img https://dl-cdn.alpinelinux.org/alpine/v3.22/releases/cloud/nocloud_alpine-3.22.1-x86_64-bios-tiny-r0.qcow2 
          mkfifo /tmp/guest.in /tmp/guest.out

      - name: Run QEMU
        id: run-qemu
        with:
          video-record: true
          #flags: 'Boot-Man/boot-man.bin'
          flags: ' -smp 4  -serial pipe:/tmp/guest  -enable-kvm alpine-x86_64.img'

          #  -usb
          #  -device       nec-usb-xhci,id=xhci
          #  -drive       if=none,id=usbstick,file=alpine-x86_64-virt-3.12.img,format=raw
          #  -device      usb-storage,id=usbdrive,bus=xhci.0,drive=usbstick 
          run: | 
          sleep 60
          (echo root;sleep 1 ;echo root; echo id -un ; echo nproc ;echo uptime; echo halt ) > /tmp/guest.in

      - name: Upload video
        uses: actions/upload-artifact@v4
        with:
          name: recording
          path: ${{ steps.run-qemu.outputs.video-output }}
