on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

#      - uses: ilammy/setup-nasm@v1

      - name: Prepare Boot-Man demo
        run: |
          #git clone https://github.com/guyhill/Boot-Man
          #cd Boot-Man
          #make
          wget -c -O- https://github.com/wenerme/alpine-image/releases/download/20200607.1/alpine-x86_64-lts-3.12.img.gz |gunzip > alpine-x86_64-virt-3.12.img
          

      - name: Run QEMU
        id: run-qemu
        uses: etchdroid/qemu-kvm-action@v1
        with:
          video-record: true
          #flags: 'Boot-Man/boot-man.bin'
          flags: 'alpine-x86_64-virt-3.12.img'

          #  -usb
          #  -device       nec-usb-xhci,id=xhci
          #  -drive       if=none,id=usbstick,file=alpine-x86_64-virt-3.12.img,format=raw
          #  -device      usb-storage,id=usbdrive,bus=xhci.0,drive=usbstick 
          run: sleep 60

      - name: Upload video
        uses: actions/upload-artifact@v4
        with:
          name: recording
          path: ${{ steps.run-qemu.outputs.video-output }}
